### ISSUE TITLE
Wikiを作る

### ISSUE THREAD

**Issue by Seasawher** [aconite-ac/aconite-ac.github.io#1]
いつもお世話になっています。

Leanの日本語情報をまとめたリンク集を作ってくださってありがとうございます。

aconiteさんの個人のサイトとして作られているようですが、パブリックなwikiのようなサイトとしてこうしたリンク集を作り直しませんか？

そこにLeanの日本語情報が集まるようにしておくと便利だと思いました。いかがでしょう

**Comment by aconite-ac** [comment]
ご提案ありがとうございます！
自分もいずれ日本語情報サイトが必要になると思っていたため、
このような提案を頂けて大変嬉しく思っています。

「aconite-ac.github.io」は元より日本語コミュニティページ、
あるいは日本語情報サイトの前身を意識して作ったサイトでしたが、

1. https対応サイトを作る上でGitHub Pagesを使う方法しか思いつかなかった以上、個人サイトをイメージさせるドメインしか取れなかった
2. サイト作成当時(TPiL4公開当時)は他のLeanの日本語ユーザーの方との交流も少なく、自分一人で進めてよいものか判断できなかった

等の理由により今の形をとったという経緯があります。

少なくとも2. については状況が変わりつつある中、Kitamadoさんよりご提案を頂き、
改めてパブリックな日本語情報サイトの設立を目指したいと思いました。

調べたところ、参考になりそうな既存の情報サイトとして[rust-jp.rs](https://rust-jp.rs/)がありました。

今のところ、自分一人で解決できなさそうな問題として、次の2点があります。

1. https対応かつパブリックな日本語情報サイトであることが分かりやすいドメインを取るにはどうしたらよいか？
2. 管理者グループ(個人・グループ・編集自由)をどのように定めたらよいか？
3. Zulip Chatのような誰でも見られるコミュニティサービスを併設したほうがよいか？

なんとなくGitHubの組織アカウントを取って信頼のおけるグループで管理するのがよい気がしていますが、
GitHubの組織アカウントの運用に関する知識に乏しいため判断しかねています。

これらの内容について、ご意見・ご提案・知識の提供等していただけると大変ありがたく思います…！

**Comment by Seasawher** [comment]
私も GitHub Organization の機能について詳しいわけではないですが，GitHub Organization を作るのはかなり良いと思います．無料でできますし，2の権限も設定できます．

また，Discussion機能があるので3も解決する気がします. （Discordのサーバーがあるのも良いことだと思うので，両方あって良いと思います）Discussion機能の活用例としては，例えば https://github.com/orgs/dbeaver/discussions をご覧ください．

1ですが，Organizationの名前を `lean-prover-jp` とか `lean-lang-jp` とかにすれば解決すると思います

**Comment by Seasawher** [comment]
私たち以外の方の意見も聞きたいので，code for math に共有してくださると助かります

**Comment by aconite-ac** [comment]
ありがとうございます、Discussion機能を知らなかったのですが、かなり良さそうに見えますね！
確かにGitHub Organizationを作る方針が目的にマッチしている気がします。

今はcode for mathの方々も自分も「数学系のためのLean勉強会」関連で忙しいかと思いますので、
自分自身GitHub Organizationについて調べてから、勉強会後にcode for mathに以下の内容を共有した後、専用のスレッドを建てたいと思います。

- [rust-jp.rs](https://rust-jp.rs/)のようなコミュニティサービス付きのパブリックなLean日本語情報サイトを作りたい
- 今のところ、GitHub Organizationアカウントを作って運用しようと思っている
- コミュニティサービスとしてDiscussion機能を使おうと思っている
- 他の方の意見も参考にしたい

**Comment by Seasawher** [comment]
勉強会お疲れさまでした

方針に賛成なのですが，https://rust-jp.rs/ は個人がホストしているサイトのように見えるので，例として良くない気がします

https://github.com/rust-lang-ja ←こういうのがより近いんじゃないでしょうか？

**Comment by aconite-ac** [comment]
勉強会お疲れ様でしたm(_ _)m

情報提供とDiscordでのスレッド建てありがとうございます！
確かに[https://github.com/rust-lang-ja](https://github.com/rust-lang-ja)とそこが運営されている[https://doc.rust-jp.rs/](https://doc.rust-jp.rs/)が、
まさしく目指しているものの前例のように見えますね。
これを例に挙げようと思います。
